println("---------start:settings.gradle.kt---------------")
include(":video")
include(":audio")
include(
        ":app",
        ":tools",
        ":annotations",
        ":storage",
        ":hack",
        ":widget",
        ":compiler",
        ":hybrid",
        ":design",
        ":image",
        ":klint",
        ":kanimation",
        ":container",
        ":media",
        ":ndk",
        ":vpn",
        ":sensor",
        ":bluetooth",
        ":nfc"
)